### ISSUE TITLE
Add camera input selection and no camera mode.

### ISSUE THREAD

**Issue by Architeuthis-Flux** [nilclass/jumperlab#1]
It's pretty early to be giving you a hard time about features, but I have a request for when you start working on this more. 

Currently, the app defaults to the built-in Facetime HD camera on my Macbook pro and I'd like to use an external webcam for this (I have a downward facing camera basically built into my workbench that would be perfect for this.)

I'll look into a fix and maybe submit a PR, but I need to work on my React skillz. 

I'm also going to work on a cartoonified Jumperless in svg format for people who don't want to mess with the webcam thing at all.

**Comment by nilclass** [comment]
Great suggestion, I'll look into it once I'm back to working on the webcam integration

**Comment by nilclass** [comment]
@Architeuthis-Flux I've [pushed some changes](https://github.com/nilclass/jumperlab/commit/e207298eb81a11f4b3c868e7e02df8d2233257df) to make the camera selectable. Does it work for you?

You should see something like this:

![Screenshot from 2024-01-08 17-53-51](https://github.com/nilclass/jumperlab/assets/104883/79f99885-80f9-47bf-896b-39f60bbc7fd8)

![Screenshot from 2024-01-08 17-53-44](https://github.com/nilclass/jumperlab/assets/104883/8815c11a-1beb-4a57-a688-14dbd62bb77b)

Not pretty, but hopefully functional.

**Comment by Architeuthis-Flux** [comment]
Yeah it works great, thanks!
